DROP TABLE IF EXISTS roles CASCADE;
DROP TABLE IF EXISTS states CASCADE;
DROP TABLE IF EXISTS tasks;
DROP TABLE IF EXISTS todo_collaborator;
DROP TABLE IF EXISTS todos;
DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS roles (
    id bigint generated by default as identity,
    name varchar(255),
    CONSTRAINT PK_role_id PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS users (
    id bigint generated by default as identity,
    email varchar(255),
    first_name varchar(255),
    last_name varchar(255),
    password varchar(255),
    role_id bigint,
    CONSTRAINT PK_user_id PRIMARY KEY (id),
    CONSTRAINT FK_role_user FOREIGN KEY (role_id) REFERENCES roles(id)
);

CREATE TABLE IF NOT EXISTS states (
    id bigint generated by default as identity,
    name varchar(255),
    CONSTRAINT PK_state_id PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS todos (
    id bigint generated by default as identity,
    created_at timestamp,
    title varchar(255),
    owner_id bigint,
    CONSTRAINT PK_todos_id PRIMARY KEY (id),
    CONSTRAINT FK_user_todo FOREIGN KEY (owner_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS tasks (
    id bigint generated by default as identity,
    name varchar(255),
    priority varchar(255),
    state_id bigint,
    todo_id bigint,
    CONSTRAINT PK_task_id PRIMARY KEY (id),
    CONSTRAINT FK_state_task FOREIGN KEY (state_id) REFERENCES states(id),
    CONSTRAINT FK_todo_task FOREIGN KEY (todo_id) REFERENCES todos(id)
);

CREATE TABLE IF NOT EXISTS todo_collaborator (
    collaborator_id bigint,
    todo_id bigint,
    CONSTRAINT FK_collaborator FOREIGN KEY (collaborator_id) REFERENCES users(id),
    CONSTRAINT FK_todo FOREIGN KEY (todo_id) REFERENCES todos(id)
);
